-- =================================================
-- MIGRATION 001: Initial Schema (Base Tables)
-- =================================================
-- These tables were originally created via Supabase Dashboard
-- This migration documents them for version control and local development

-- -------------------------------------------------
-- CHALLENGES TABLE
-- Core table storing all challenge definitions
-- -------------------------------------------------
CREATE TABLE challenges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL DEFAULT '',
  description TEXT,
  estimated_time TEXT,
  difficulty TEXT,
  completion_criteria TEXT,
  category TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  points BIGINT
);

-- Unique constraint on id (matches remote)
ALTER TABLE challenges ADD CONSTRAINT challenges_id_key UNIQUE (id);

-- Enable Row Level Security (RLS)
ALTER TABLE challenges ENABLE ROW LEVEL SECURITY;

-- Policy: Anyone can read challenges (public)
CREATE POLICY "Enable read access for all users"
  ON challenges
  FOR SELECT
  TO public
  USING (true);

-- -------------------------------------------------
-- USER_CHALLENGES TABLE
-- Junction table tracking which users saved which challenges
-- -------------------------------------------------
CREATE TABLE user_challenges (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  challenge_id BIGINT NOT NULL REFERENCES challenges(id) ON DELETE CASCADE,
  added_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT user_challenges_user_id_challenge_id_key UNIQUE (user_id, challenge_id)
);

-- Index for efficient user lookups
CREATE INDEX idx_user_challenges_user_id ON user_challenges(user_id);
CREATE INDEX idx_user_challenges_challenge_id ON user_challenges(challenge_id);

-- Enable RLS (policies added in migration 004)
ALTER TABLE user_challenges ENABLE ROW LEVEL SECURITY;

-- Private RLS policies - users can only see/modify their own list
CREATE POLICY "Users can view own list"
  ON user_challenges FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own list"
  ON user_challenges FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own list"
  ON user_challenges FOR DELETE
  USING (auth.uid() = user_id);
